# Generated by Django 4.2.3 on 2024-05-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0006_doctoredutcation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorEdutcation',
            new_name='DoctorEducation',
        ),
        migrations.RenameField(
            model_name='doctoreducation',
            old_name='end',
            new_name='en',
        ),
    ]
