# Generated by Django 4.2.3 on 2024-05-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0007_rename_doctoredutcation_doctoreducation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoreducation',
            old_name='en',
            new_name='end',
        ),
    ]
