# Generated by Django 4.2.3 on 2024-05-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0009_patient_patientappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_users.doctor'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='doctor_name',
            field=models.CharField(default='56', max_length=1000),
            preserve_default=False,
        ),
    ]
